version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2
  aws-cli: circleci/aws-cli@3.1.1
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.1
  terraform: circleci/terraform@3.1.0

jobs:
  run_tests:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
          cache-path: ~/project/node_modules
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mocha-junit-reporter --reporter-options mochaFile=./test/test-results.xml
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test/
      - store_artifacts:
          path: test-results
  scan_app:
    docker:
      - image: snyk/snyk:node-14
    steps:
      - checkout
      - run:
          name: Snyk Scan Application files 
          command: npm install 
      - run:
          name: Snyk Scans
          command: |
            echo '' && echo 'Snyk Code' && echo ''
            snyk code test --org=demo_high  || true
            echo '' && echo 'Snyk OpenSource' && echo ''
            snyk test --org=demo_high --all-projects --remote-repo-url=$CIRCLE_PROJECT_REPONAME || true
            echo '' && echo 'Snyk IaC' && echo ''
            snyk iac test --org=demo_high || true
  build_docker_image:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout  
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.<< pipeline.number >>
      - run:
          name: Snyk Container 
          command: docker run --rm -it --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=$CIRCLE_PROJECT_REPONAME --app-vulns --nested-jars-depth=8 $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:0.1.<< pipeline.number >> || true
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.<< pipeline.number >>
  deploy_aws_ecs:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Create .terraformrc file locally
          command: echo "credentials \"app.terraform.io\" {token = \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - terraform/install:
          terraform_version: "1.0.2"
          arch: "amd64"
          os: "linux"
      - terraform/init:
          path: ./terraform/ecs
      - terraform/plan:
          path: ./terraform/ecs
      - run:
          name: Terraform apply
          command: |
            terraform -chdir=./terraform/ecs apply \
              -var docker_img_name=${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME} \
              -var docker_img_tag=0.1.<< pipeline.number >> \
              -auto-approve
            export ENDPOINT="$(terraform -chdir=./terraform/ecs output load_balancer_hostname)"
            mkdir -p /tmp/ecs/
            echo 'export ENDPOINT='${ENDPOINT} > /tmp/ecs/endpoint
      - persist_to_workspace:
          root: /tmp/ecs/
          paths:
            - "*"      
      - run: sleep 90
  smoketest_deployment:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/ecs/
      - run:
          name: Smoke Test ECS Deployment
          command: |
            source /tmp/ecs/endpoint
            ./test/smoke_test $ENDPOINT
  destroy_aws_ecs:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Create .terraformrc file locally
          command: echo "credentials \"app.terraform.io\" {token = \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - terraform/install:
          terraform_version: "1.0.2"
          arch: "amd64"
          os: "linux"
      - terraform/init:
          path: ./terraform/ecs
      - terraform/plan:
          path: ./terraform/ecs
      - terraform/destroy:
          path: ./terraform/ecs
workflows:
  build:
    jobs:
      - run_tests:
          context:
            - snyk_demo
      - scan_app:
          context:
            - snyk_demo
          requires:
            - run_tests
      - build_docker_image:
          context:
            - snyk_demo
          requires:
            - scan_app
      - deploy_aws_ecs:
          context:
            - snyk_demo
          requires:
            - build_docker_image          
      - smoketest_deployment:
          context:
            - snyk_demo
          requires:
            - deploy_aws_ecs
      - approve_destroy:
          context:
            - snyk_demo
          type: approval
          requires:
            - smoketest_deployment
      - destroy_aws_ecs:
          context:
            - snyk_demo
          requires:
            - approve_destroy

